var Localisation = {
	UA: {
		"nav":{
			"search" : "Пошук",
			"main" : "Головна",
			"channels" : "Канали",
			"archive" : "Крхiв",
			"cinema" : "Кiно",
			"radio" : "Радiо",
			"cabinet" : "Кабiнет",
			"exit" : "Выхiд",
			"back_home" : "На головну",
		},

		"muvies_info" : {
			"muvies_duration" : "Тривалість",
			"audio_language" : "Мова аудіо",
			"rating" : "Рейтинг",
			"actors" : "Актори",
			"recorded" : "Запис від",
			"cannel" : "Канал",
			"available" : "Доступно ще",
			"look_btn" : "Дивитись",
			"watch_later_btn" : "Переглянути пізніше",
			"buy_btn" : "Купити",
			"more_btn" : "Детальніше",
			"category_empty": "На жаль дана категорія порожня",
			"all" : "Всi",
			"empty_page" : "Упс! Ми не знайшли данных по цьому запиту",
		},
		"time_counter" : {
			"years" : "р", 
			"month": "міс",
			"days": "д",
			"hours": "год",
			"minutes": "хв",
		},
		"monthes" : {
			"1" : "січня",
			"2" : "лютого",
			"3" : "березня",
			"4" : "квітня",
			"5" : "травня",
			"6" : "червня",
			"7" : "липня",
			"8" : "серпня",
			"9" : "вересня",
			"10" : "жовтря",
			"11" : "листопада",
			"12" : "грудня",
		},
		"pages": {
			"search" : "Що будемо шукаты?",
			"error301": "Здаеться щось пішло не так і фільм зник :(",
		},
			
	},
	
	RU: {
		"nav":{
			"search" : "Поиск",
			"main" : "Главная",
			"channels" : "Каналы",
			"archive" : "Архив",
			"cinema" : "Кинотеатр",
			"radio" : "Радио",
			"cabinet" : "Кабинет",
			"exit" : "Выход",
			"back_home" : "На главную",
		},

		"muvies_info" : {
			"muvies_duration" : "Длительность",
			"audio_language" : "Язык аудио",
			"rating" : "Рейтинг",
			"actors" : "Актеры",
			"recorded" : "Запись от",
			"cannel" : "Канал",
			"available" : "Доступно еще",
			"look_btn" : "Смотреть",
			"watch_later_btn" : "Посмотреть позже",
			"buy_btn" : "Купить",
			"more_btn" : "Подробнее",
			"category_empty": "К сожалению данная категария пуста",
			"all" : "Все",
			"empty_page" : "Упс! К сожалению мы не нашли данных по Вашему запросу",
		},
		"time_counter" : {
			"years" : "г",
			"month": "мес",
			"days": "д",
			"hours": "час",
			"minutes": "мин",
		},
		"monthes" : {
			"1" : "января",
			"2" : "февраля",
			"3" : "марта",
			"4" : "апреля",
			"5" : "мая",
			"6" : "июня",
			"7" : "июля",
			"8" : "августа",
			"9" : "сентября",
			"10" : "октября",
			"11" : "ноября",
			"12" : "декабря",
		},
		"pages": {
			"search" : "Что будем искать?",
			"error301" : "Кажется что-то пошло не по плану и фильм пропал :("
		},
			
	},
	EN: {
		"nav":{
			"search" : "Search",
			"main" : "Main",
			"channels" : "Channels",
			"archive" : "Archive",
			"cinema" : "Cinema",
			"radio" : "Radio",
			"cabinet" : "Cabinet",
			"exit" : "Exit",
			"back_home" : "Back home",
		},

		"muvies_info" : {
			"muvies_duration" : "Duration",
			"audio_language" : "Audio language",
			"rating" : "Rating",
			"actors" : "Actors",
			"recorded" : "Recorded from",
			"cannel" : "Cannel",
			"available" : "Available for",
			"look_btn" : "Look",
			"watch_later_btn" : "Watch later",
			"buy_btn" : "Buy",
			"more_btn" : "Read more",
			"category_empty": "Unfortunately this category are empty",
			"all" : "All",
			"empty_page" : "Oops! Nothing to see here"
		},
		"time_counter" : {
			"years" : "years",
			"month": "month",
			"days": "d",
			"hours": "hours",
			"minutes": "min",
		},
		"monthes" : {
			"1" : "January",
			"2" : "February",
			"3" : "March",
			"4" : "April",
			"5" : "May",
			"6" : "June",
			"7" : "July",
			"8" : "August",
			"9" : "September",
			"10" : "October",
			"11" : "November",
			"12" : "December",
		},
		"pages": {
			"search" : "what are we looking for?",
			"error301" : "Wow! It seems like we lost this video :("
		},
		
	},

};